"use client";

import NavBar from "./components/navbar/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Analytics } from "@vercel/analytics/react";
import { CartProvider } from "react-use-cart";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });
//
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <SessionProvider>
      <CartProvider>
        <html lang="en">
          <body className="app">
            <NavBar />
            {children}
            <Analytics />
          </body>
        </html>
      </CartProvider>
    </SessionProvider>
  );
}
